name: openmeteo-weather-forecast-get-weather-forecast-corvalis

on:
    workflow_dispatch:
        inputs:
            OVERWRITTEN:
                description: "Overwritten fields"
                required: true
            PAYLOAD_URL:
                description: "URL to payload"
                required: true

jobs:
    run_docker_image:
        runs-on: ubuntu-latest
        container: ghcr.io/faasr/github-actions-r:latest

        env:
            GH_PAT: ${{ secrets.GH_PAT}}
            MINIO_AccessKey: ${{ secrets.MINIO_AccessKey}}
            MINIO_SecretKey: ${{ secrets.MINIO_SecretKey}}
            OVERWRITTEN: ${{ github.event.inputs.OVERWRITTEN }}
            PAYLOAD_URL: ${{ github.event.inputs.PAYLOAD_URL }}

        steps:
          - name: Install patched FaaSr backend
            run: |
                python3 -m pip install --upgrade --force-reinstall --break-system-packages "git+https://github.com/dekkov/FaaSr-Backend.git"
          - name: Run Python entrypoint
            run: |
                cd /action
                python3 faasr_entry.py
